name: CI

on:
  push:
    branches: [master]
    paths:
      - "*.tex"
      - "preguntas/*.tex"
      - .latexmkrc

  pull_request:
    branches: [master]
    paths:
      - "*.tex"
      - "preguntas/*.tex"
      - .latexmkrc

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Linter de LaTeX
        uses: j2kun/chktex-action@v1.0.2

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Compilar
      - name: Compilador de LuaTeX
        uses: dante-ev/latex-action@v0.2.0
        with:
          # Archivo a Compilar
          root_file: documento.tex

      - name: Subir log del compilador
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: document.log
          # A file, directory or wildcard pattern that describes what to upload
          path: /home/runner/work/plantilla-uc/plantilla-uc/documento.log
