name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Linter de LaTeX
        uses: j2kun/chktex-action@v1.0.2

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Compilar
      - name: Compilador de LuaTeX
        uses: dante-ev/latex-action@v0.2.0
        with:
          # Archivo a Compilar
          root_file: documento.tex
          # Usar LuaLateX
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
